"""
Root-Cause Engine.

Generates docs-style root-cause narratives (Problem -> Evidence -> Root
Cause -> Action -> Expected Impact, using 5-Why logic) for the worst lanes
and carrier/lane combinations, instead of a flat "Carrier B is poor"
statement. Writes outputs/root_cause_analysis.md.
"""

from pathlib import Path
import sys

import pandas as pd

ROOT_DIR = Path(__file__).resolve().parent.parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from config.config import (  # noqa: E402
    CARRIER_LANE_SCORECARD_PATH,
    FEATURED_SHIPMENTS_PATH,
    LANE_SCORECARD_PATH,
    MIN_VOLUME_FOR_RECOMMENDATION,
    OUTPUTS_DIR,
    ROOT_CAUSE_PATH,
)
from src.lane_engine.lane_intelligence import explain_lane  # noqa: E402


def five_why_for_lane(df: pd.DataFrame, cl_df: pd.DataFrame, lane_row: pd.Series) -> list:
    city, lane_class = lane_row["customer_city"], lane_row["lane_class"]
    lane_shipments = df[(df["customer_city"] == city) & (df["lane_class"] == lane_class) & (~df["is_open"])]

    whys = [f"1. WHY did {city} ({lane_class}) miss its EDD target? "
            f"Because EDD adherence is {lane_row['edd_adherence_pct']}% vs the 85% network baseline."]

    ndr_share = lane_shipments["has_ndr"].mean()
    top_reason = (
        lane_shipments.loc[lane_shipments["has_ndr"], "ndr_reason"].value_counts().idxmax()
        if lane_shipments["has_ndr"].any() else None
    )
    whys.append(f"2. WHY is EDD adherence low here? Because {ndr_share:.0%} of shipments on this lane "
                f"had at least one NDR event" + (f", most commonly '{top_reason}'." if top_reason else "."))

    carrier_mix = lane_shipments.groupby("carrier")["edd_met"].mean().sort_values()
    worst_carrier = carrier_mix.index[0] if len(carrier_mix) else "n/a"
    worst_carrier_rate = carrier_mix.iloc[0] if len(carrier_mix) else None
    whys.append(f"3. WHY does this lane have elevated NDR? Contributing carrier-mix signal: "
                f"{worst_carrier} shows the lowest EDD rate on this lane "
                f"({worst_carrier_rate:.0%})." if worst_carrier_rate is not None else
                "3. WHY does this lane have elevated NDR? Insufficient carrier-level sample to isolate a cause.")

    p90 = lane_row["p90_transit_days"]
    sla = df[(df["customer_city"] == city) & (df["lane_class"] == lane_class)]["transit_sla_days"].iloc[0] if len(lane_shipments) else None
    whys.append(f"4. WHY does that translate into late deliveries? P90 transit time is {p90} days against "
                f"a {sla}-day transit SLA for {lane_class} lanes — the tail of shipments structurally "
                f"cannot make EDD once transit exceeds SLA.")

    whys.append(f"5. WHY hasn't this self-corrected? Shipment volume on this lane ({lane_row['shipment_volume']}) "
                f"is below the {MIN_VOLUME_FOR_RECOMMENDATION}-shipment threshold ops typically needs before "
                f"reallocating carrier capacity — it has been below the radar of lane-level carrier reviews.")

    return whys


def generate_report(df: pd.DataFrame, lane_df: pd.DataFrame, cl_df: pd.DataFrame) -> str:
    lines = ["# Root-Cause Analysis — EDD Adherence Gap\n",
             "Auto-generated by `src/decision_engine/root_cause.py`. Every claim below cites the "
             "underlying evidence from `outputs/lane_scorecard.csv` and `data/processed/shipments_features.csv` "
             "— nothing here is asserted without a number behind it.\n"]

    worst = lane_df[lane_df["lane_status"].isin(["Intervention Required", "Deteriorating"])].sort_values("lane_health_score").head(5)
    for _, r in worst.iterrows():
        exp = explain_lane(r)
        lines.append(f"## {r['customer_city']} ({r['lane_class']}) — Lane Health {r['lane_health_score']}\n")
        lines.append(f"**Problem:** {exp['what']}\n")
        lines.append(f"**Evidence:** {exp['evidence']}\n")
        lines.append("**Root cause (5-Why):**\n")
        for why in five_why_for_lane(df, cl_df, r):
            lines.append(f"- {why}")
        lines.append(f"\n**Recommended action:** {exp['action']}\n")
        lines.append(f"**Expected impact:** {exp['expected_impact']}\n")
        lines.append("---\n")

    return "\n".join(lines)


def run():
    df = pd.read_csv(FEATURED_SHIPMENTS_PATH, parse_dates=["order_date", "pickup_date", "first_attempt_date", "delivery_date", "edd"])
    lane_df = pd.read_csv(LANE_SCORECARD_PATH)
    cl_df = pd.read_csv(CARRIER_LANE_SCORECARD_PATH)
    report = generate_report(df, lane_df, cl_df)
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    with open(ROOT_CAUSE_PATH, "w") as f:
        f.write(report)
    print(f"Wrote root-cause report -> {ROOT_CAUSE_PATH}")
    return report


if __name__ == "__main__":
    run()
